from crewai import Task

class AutoDSTasks:
    def research_task(self, agent, dataset_topic):
        return Task(
            description=(
                f"1. Use the Search Tool to find the top Kaggle dataset related to '{dataset_topic}'. "
                "2. Identify the key columns and the target variable (if any). "
                "3. Create a numbered list of 3 specific EDA (Exploratory Data Analysis) steps "
                "that the Code Agent should perform (e.g., 'Check for missing values', "
                "'Plot distribution of Age', 'Correlation heatmap')."
            ),
            expected_output="A brief text summary of the dataset and a numbered execution plan.",
            agent=agent
        )

    def coding_task(self, agent):
        return Task(
            description=(
                "You have a Python environment. Execute the plan provided by the Research Agent. "
                "1. START by creating a dummy DataFrame based on the research description. "
                "2. Execute the 3 EDA steps from the plan. "
                "3. If any code fails, analyze the error and Retry. "
                "4. CRITICAL: When printing data, use 'print(df.head(3))' (only 3 rows). " # Strict limit
                "5. Do NOT print the full DataFrame description. Use 'print(df.describe().iloc[:3])' if needed. "
                "6. Generate a simple plot and save it."
            ),
            expected_output="Executed code logs and success confirmation.",
            agent=agent,
            context=[] 
        )

    def review_task(self, agent):
        return Task(
            description=(
                "Review the code and output generated by the Python Data Science Developer. "
                "1. Check if the code ran successfully without errors. "
                "2. Check if the numbers/stats make logical sense. "
                "3. If the quality is poor, note the specific issues. "
                "4. Provide a 'Pass/Fail' grade and a short critique."
            ),
            expected_output="A short review report with a Pass/Fail grade and feedback.",
            agent=agent
        )

    def reporting_task(self, agent):
        return Task(
            description=(
                "Review all previous steps (Research, Code Execution, Review). "
                "Summarize the findings into a professional Markdown report. "
                "The report should have: "
                "- Title "
                "- Dataset Overview "
                "- Methodology (what cleaning/analysis was done) "
                "- Key Insights (from the code outputs) "
                "- Conclusion "
                "Use the 'Context Compaction' technique: keep it concise, avoiding long code dumps."
            ),
            expected_output="A final Markdown formatted report.",
            agent=agent,
            output_file='output/final_report.md' # This saves the result to a file!
        )